function init(self)
	msg.post("#collectionproxy", "async_load")
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "acquire_input_focus")
		msg.post(sender, "enable")
	elseif message_id == hash("proxy_unloaded") then
		msg.post(sender, "async_load")
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
