embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.5\n"
  "restitution: 0.75\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "mask: \"entity\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 31.0\n"
  "  data: 31.0\n"
  "  data: 0.5\n"
  "}\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "objectinterpolation"
  type: "objectinterpolation"
  data: "apply_transform: APPLY_TRANSFORM_RENDER\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"block_fall\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 66.0\n"
  "  y: 66.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/test/2d/sprites.atlas\"\n"
  "}\n"
  ""
}
